---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbdata-chris.farhood.org
  labels:
    name: dbdata-chris.farhood.org
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "longhorn"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
  labels:
    name: dbdata
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests: 
      storage: 8Gi
  volumeName: dbdata-chris.farhood.org

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wwwdata-chris.farhood.org
  labels:
    name: wwwdata-chris.farhood.org
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs"
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/sites/farhood.org/chris
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwdata
  labels:
    name: wwwdata
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests: 
      storage: 1Gi
  volumeName: wwwdata-chris.farhood.org