---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
   app.kubernetes.io/name: wordpress
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/name: wordpress
    tier: web
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: wordpress
  annotations:
    polaris.fairwinds.com/runAsRootAllowed-exempt: true  
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
      tier: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress
        tier: web
    spec:
      containers:
      - name: wordpress
        image: wordpress:php8.3
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: password
        - name: WORDPRESS_DB_USER
          value: wordpress
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: wwwdata
          mountPath: "/var/www/html"
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
      volumes:
      - name: wwwdata
        persistentVolumeClaim:
          claimName: wwwdata
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - wordpress
            topologyKey: "kubernetes.io/hostname"    
